---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:1.21.*
spec:
  releaseName: jenkins
  chart:
    repository: stable
    name: jenkins
    version: 1.9.12
